#!/bin/bash

# --------------------------------------------
# 🔹 Configure Host 1 (host_fech-cha-1)
# --------------------------------------------

# Assign an IP to eth1 (Connects to VXLAN network)
ip addr add 30.1.1.1/24 dev eth1