FROM frrouting/frr:latest

RUN echo 'service integrated-vtysh-config' > /etc/frr/vtysh.conf && \
    sed -i \
    -e 's/bgpd=no/bgpd=yes/g' \
    -e 's/ospfd=no/ospfd=yes/g' \
    -e 's/isisd=no/isisd=yes/g' \
    -e 's/zebra=no/zebra=yes/g' \
    /etc/frr/daemons

RUN apk update && apk add --no-cache \
    iproute2 \
    iputils \
    nano \
    vim \
    net-tools \
    netcat-openbsd \
    BusyBox

RUN chmod 777 /etc/frr/ && chown frr:frr /etc/frr/*

EXPOSE 179 2601 2604 2608
